(()=>{'use strict';if(window.__DORI_SOUND__)return;window.__DORI_SOUND__=true;
const K='doriSoundSettings.v1',D={enabled:true,volume:100};let S={...D};try{const x=JSON.parse(localStorage.getItem(K)||'null');if(x&&typeof x==='object'){S.enabled=x.enabled!==false;S.volume=Math.max(0,Math.min(100,Number(x.volume??100)))}}catch(e){}
let ac;function ctx(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!ac)ac=new C();if(ac.state==='suspended')ac.resume().catch(()=>{});return ac}
function tone(f=650,e=500,d=.08,g=.12,w='sine',delay=0){if(!S.enabled||S.volume<=0)return;const c=ctx();if(!c)return;const t=c.currentTime+delay,o=c.createOscillator(),a=c.createGain(),q=c.createBiquadFilter();o.type=w;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,e),t+d);q.type='lowpass';q.frequency.value=4800;a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(g*S.volume/100,t+.012);a.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(q);q.connect(a);a.connect(c.destination);o.start(t);o.stop(t+d+.01)}
const fx={click:()=>tone(760,540,.055,.1),open:()=>{tone(440,720,.12,.11);tone(660,980,.1,.07,'sine',.04)},close:()=>tone(700,400,.1,.1),success:()=>{tone(523,523,.13,.12);tone(659,659,.14,.12,'sine',.08);tone(784,1047,.2,.12,'sine',.16)},coin:()=>{tone(1046,1320,.09,.12);tone(1568,1760,.12,.1,'sine',.07)},error:()=>tone(260,180,.17,.12,'triangle'),move:()=>tone(420,590,.07,.1),attack:()=>{tone(230,90,.15,.17,'triangle');tone(110,65,.12,.1,'sine',.03)},win:()=>{tone(392,392,.14,.12);tone(523,523,.14,.12,'sine',.1);tone(659,659,.14,.12,'sine',.2);tone(784,1047,.25,.13,'sine',.3)},dog:()=>{tone(330,180,.1,.15,'triangle');tone(260,145,.1,.14,'triangle',.13)},doronum:()=>{tone(880,1320,.2,.1);tone(1760,2200,.24,.08,'sine',.1)}};
function play(n='click'){(fx[n]||fx.click)()}function save(){try{localStorage.setItem(K,JSON.stringify(S))}catch(e){};ui()}
document.addEventListener('click',e=>{const el=e.target.closest?.('button,a,[role=button],input[type=button],input[type=submit]');if(!el||el.closest('#dori-sound-panel')||el.id==='dori-sound-toggle'||el.dataset.soundIgnore==='true')return;const t=(el.getAttribute('aria-label')||el.innerText||'').slice(0,80);const n=/실패|오류|부족/.test(t)?'error':/승리|완료|성공|달성|획득/.test(t)?'success':/코인|구매|보상|매수|매도|판매/.test(t)?'coin':/공격|전투|스킬/.test(t)?'attack':/메뉴|설정|시작|다음/.test(t)?'open':/닫기|뒤로/.test(t)?'close':'click';play(n)},true);
document.addEventListener('dori:sound',e=>{const n=typeof e.detail==='string'?e.detail:e.detail?.name;if(n)play(n)});
const css=document.createElement('style');css.textContent=`#dori-sound-widget{position:fixed;right:max(14px,env(safe-area-inset-right));bottom:max(14px,env(safe-area-inset-bottom));z-index:2147483000;font:13px/1.4 inherit;color:#f5f7ff}#dori-sound-toggle{display:flex;align-items:center;gap:9px;border:1px solid #ffffff35;border-radius:999px;padding:11px 15px;background:linear-gradient(135deg,#131c48f5,#05081cf5);box-shadow:0 8px 30px #0006,inset 0 1px #ffffff18;color:inherit;font:inherit;font-weight:700;cursor:pointer;backdrop-filter:blur(16px)}#dori-sound-toggle:hover{border-color:#9aaaffaa;transform:translateY(-1px)}#dori-sound-led{width:7px;height:7px;border-radius:50%;background:#65e6b0;box-shadow:0 0 12px #65e6b0aa}#dori-sound-widget[data-off=true] #dori-sound-led{background:#8790a8;box-shadow:none}#dori-sound-panel{position:absolute;right:0;bottom:calc(100% + 10px);width:min(290px,calc(100vw - 28px));padding:17px;border:1px solid #ffffff30;border-radius:19px;background:linear-gradient(145deg,#12193efa,#05081afa);box-shadow:0 20px 60px #0007;backdrop-filter:blur(20px);transform-origin:bottom right;animation:dsIn .18s ease-out}#dori-sound-panel[hidden]{display:none}#dori-sound-panel .dsrow{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:14px 0}#dori-sound-panel .dssub{font-size:11px;color:#aeb9da;margin-top:4px}#dori-sound-panel input[type=range]{width:100%;accent-color:#9aaaff}#dori-sound-panel .dsval{color:#dbe2ff;min-width:42px;text-align:right;font-variant-numeric:tabular-nums}#dori-sound-panel button{width:100%;margin-top:12px;padding:10px;border:1px solid #aabaff40;border-radius:11px;background:#828fff20;color:inherit;font:inherit;cursor:pointer}@keyframes dsIn{from{opacity:0;transform:translateY(5px) scale(.98)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){#dori-sound-panel{animation:none}}`;document.head.appendChild(css);
const w=document.createElement('div');w.id='dori-sound-widget';w.innerHTML='<section id="dori-sound-panel" hidden aria-label="효과음 설정"><div style="font-weight:750;font-size:15px">사운드 컨트롤</div><div class="dssub">DORI DIGITAL AUDIO</div><div class="dsrow"><label for="dori-sound-enabled">효과음 켜기</label><input id="dori-sound-enabled" type="checkbox"></div><div class="dsrow"><label for="dori-sound-volume">기본 음량</label><span id="dori-sound-value" class="dsval">100%</span></div><input id="dori-sound-volume" type="range" min="0" max="100" value="100" aria-label="효과음 음량"><button id="dori-sound-test" type="button">♪ 사운드 미리 듣기</button></section><button id="dori-sound-toggle" type="button" aria-expanded="false" aria-controls="dori-sound-panel"><span id="dori-sound-led"></span><span id="dori-sound-label">효과음 켜짐</span><span aria-hidden="true">⌄</span></button>';document.body.appendChild(w);
const p=w.querySelector('#dori-sound-panel'),b=w.querySelector('#dori-sound-toggle'),en=w.querySelector('#dori-sound-enabled'),vol=w.querySelector('#dori-sound-volume'),val=w.querySelector('#dori-sound-value'),lab=w.querySelector('#dori-sound-label');
function ui(){if(!w.isConnected)return;en.checked=S.enabled;vol.value=S.volume;vol.disabled=!S.enabled;val.textContent=S.volume+'%';lab.textContent=S.enabled?'효과음 켜짐':'효과음 꺼짐';w.dataset.off=String(!S.enabled)}
b.addEventListener('click',()=>{p.hidden=!p.hidden;b.setAttribute('aria-expanded',String(!p.hidden));if(!p.hidden)play('open')});en.addEventListener('change',()=>{S.enabled=en.checked;save();if(S.enabled)play('success')});vol.addEventListener('input',()=>{S.volume=Number(vol.value);save()});w.querySelector('#dori-sound-test').addEventListener('click',()=>{if(!S.enabled)S.enabled=true;save();play('success')});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!p.hidden){p.hidden=true;b.setAttribute('aria-expanded','false')}});ui();
window.DoriSound=Object.freeze({play,setEnabled(v){S.enabled=!!v;save()},setVolume(v){S.volume=Math.max(0,Math.min(100,Number(v)||0));save()},getSettings(){return {...S}}});
})();